### ISSUE TITLE
Fail on npm run dev

### ISSUE THREAD

**Issue by kerns** [lelouchB/next-cloudinary-lightroom#3]
**Describe the bug**
Sounded like an interesting project, just testing, but didn't get too far.

```
❯ npm run dev

> next-cloudinary-lightroom@0.1.0 dev
> next dev

ready - started server on 0.0.0.0:3000, url: http://localhost:3000
Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: Package subpath './lib/parser' is not defined by "exports" in /Users/dvk/Sites/projects/next-lr/node_modules/postcss/package.json
    at new NodeError (node:internal/errors:393:5)
    at throwExportsNotFound (node:internal/modules/esm/resolve:358:9)
    at packageExportsResolve (node:internal/modules/esm/resolve:668:3)
    at resolveExports (node:internal/modules/cjs/loader:529:36)
    at Module._findPath (node:internal/modules/cjs/loader:569:31)
    at Module._resolveFilename (node:internal/modules/cjs/loader:981:27)
    at mod._resolveFilename (/Users/dvk/Sites/projects/next-lr/node_modules/next/dist/build/webpack/require-hook.js:4:1784)
    at Module._load (node:internal/modules/cjs/loader:841:27)
    at Module.require (node:internal/modules/cjs/loader:1061:19)
    at require (node:internal/modules/cjs/helpers:103:18)
    at 552 (/Users/dvk/Sites/projects/next-lr/node_modules/next/dist/compiled/postcss-scss/scss-syntax.js:1:11590)
    at __nccwpck_require__ (/Users/dvk/Sites/projects/next-lr/node_modules/next/dist/compiled/postcss-scss/scss-syntax.js:1:11735)
    at 270 (/Users/dvk/Sites/projects/next-lr/node_modules/next/dist/compiled/postcss-scss/scss-syntax.js:1:400)
    at __nccwpck_require__ (/Users/dvk/Sites/projects/next-lr/node_modules/next/dist/compiled/postcss-scss/scss-syntax.js:1:11735)
    at 327 (/Users/dvk/Sites/projects/next-lr/node_modules/next/dist/compiled/postcss-scss/scss-syntax.js:1:260)
    at __nccwpck_require__ (/Users/dvk/Sites/projects/next-lr/node_modules/next/dist/compiled/postcss-scss/scss-syntax.js:1:11735) {
  code: 'ERR_PACKAGE_PATH_NOT_EXPORTED'
}
```

**Comment by lelouchB** [comment]
Hey @kerns 

I will look into it and fix it.
Probably soles issues with package versions.

Thanks

**Comment by lelouchB** [comment]
@kerns 
I will be archiving this repo, I think the Lightroom plugin is no longer on Cloudinary. If you still want to run this project, please let me know and I will fix the error
